// Code generated by tools/contentgen; DO NOT EDIT.

package gameplay

var upgradeDefinitions = map[string]UpgradeDefinition{
	"upgrade_parallel_slots":   UpgradeDefinition{Key: "upgrade_parallel_slots", Name: "Queue Throughput", Summary: "Expand how many behaviors you can run concurrently.", Category: "Queue Capacity", GateTypes: []string{"resource"}, CostScaling: 1.6, Costs: map[string]int64{"coins": 40}, Outputs: UpgradeOutputDefinition{QueueSlotsDelta: 1}},
	"upgrade_recovery_routine": UpgradeDefinition{Key: "upgrade_recovery_routine", Name: "Recovery Routine", Summary: "Improve passive stamina regeneration each purchase.", Category: "Stamina", GateTypes: []string{"resource"}, CostScaling: 1.45, OutputScaling: 1.2, Costs: map[string]int64{"coins": 30}, Outputs: UpgradeOutputDefinition{StatDeltas: map[string]int64{"stamina_recovery_rate": 1}}},
}
